[theme]
font = "sans-serif"
base = "light"
primaryColor = "#0D2B5E"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A202C"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
headless = true
